name: consensus
on:
  pull_request:
  push:
    branches: # pushing tags is also considered as a push. Exclude this here.
      - "*" 
  schedule:
    - cron: "0 0 * */3 0" # https://crontab.guru/#0_0_*_*/3_0
jobs:
  consensusCTF:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@main
        - uses: actions/setup-go@main
          with:
            go-version: 1.20
        - run: go test -v ./... --count=1
          name: go test
          working-directory: consensusCFT

  consensusPBFT:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@main
        - uses: actions/setup-go@main
          with:
            go-version: 1.20
        - run: go test -v ./... --count=1
          name: go test
          working-directory: consensusPBFT